/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jForm;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class test extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void printRecord(JPanel panel){
        PrinterJob printerJob=PrinterJob.getPrinterJob();
        // Set Printer Job Name
        printerJob.setJobName("Print");
        // Set Printable
        printerJob.setPrintable(new Printable(){
            @Override
            public int print(Graphics graphics,PageFormat pageFormat,int pageIndex) throws PrinterException{
            // Check If No Printable Content
                if(pageIndex>0)
                {
                    return Printable.NO_SUCH_PAGE;
                }

                // Make 2D Graphics to map content
                Graphics2D graphics2D=(Graphics2D)graphics;
                // Set Graphics Translations
                graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
                // This isapage scale.Default should be 0.3 I am using 0.5
                graphics2D.scale(0.5,0.5);
                // Now paint panel as graphics2D
                panel.paint(graphics2D);
                // return if page exists
                return Printable.PAGE_EXISTS;
                
            }
        });
        // Store printerDialog as boolean
        boolean returningResult=printerJob.printDialog();
        // check if dilog is showing
        if(returningResult){
        // Use try catch exeption for failure
            try{
                // Now call print method inside printerJob to print
                printerJob.print();
            }
            catch(PrinterException printerException){
            JOptionPane.showMessageDialog(this,"Print Error:"+printerException.getMessage());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
