/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jForm;

import define.User;
import define.Xe;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import quanlybaigiuxe.QuanLyBaiGiuXe;

/**
 *
 * @author pc
 */
public class ThanhToanFrame extends javax.swing.JFrame {
    QuanLyBaiGiuXe quanLyXe;
    Xe xe;
    User user;
    /**
     * Creates new form ThanhToanFrame
     */
    public ThanhToanFrame() {
        initComponents();
    }
    public ThanhToanFrame(Xe xe1) {
        initComponents();
        xe = new Xe(xe1);
        quanLyXe = new QuanLyBaiGiuXe();
        Date date= new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm dd-MM-yyyy");
        String dateNow = formatter.format(date);
        
        
        txtMaXeTT.setText(xe.getIdXe());
        txtBienSoTT.setText(xe.getBienSo());
        txtThoiGianVaoTT.setText(stringToStringDate(xe.getTimeVao()));
        txtThoiGianRaTT.setText(dateNow);
        
        float tongtien=quanLyXe.getPaymentById(xe.getIdXe());
        System.out.println(tongtien);
        txtSumTT.setText(String.valueOf(tongtien));
        txtTienDaThuTT.setText(String.valueOf(xe.getTienDaThu()));
        
        txtTienPhaiThuTT.setText(String.valueOf( tongtien-xe.getTienDaThu() ));
        System.out.println(quanLyXe.getPaymentById(xe.getIdXe()));
        
        btSubmitTT.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmain = new javax.swing.JPanel();
        btSubmitTT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbMaXeTT = new javax.swing.JLabel();
        lbBienSoTT = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtMaXeTT = new javax.swing.JTextField();
        txtBienSoTT = new javax.swing.JTextField();
        txtThoiGianVaoTT = new javax.swing.JTextField();
        txtThoiGianRaTT = new javax.swing.JTextField();
        txtSumTT = new javax.swing.JTextField();
        txtTienDaThuTT = new javax.swing.JTextField();
        txtTienPhaiThuTT = new javax.swing.JTextField();
        btexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thanh toán");
        setUndecorated(true);

        panelmain.setBackground(new java.awt.Color(245, 245, 245));

        btSubmitTT.setBackground(new java.awt.Color(0, 255, 51));
        btSubmitTT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSubmitTT.setForeground(new java.awt.Color(255, 255, 255));
        btSubmitTT.setText("XÁC NHẬN");
        btSubmitTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitTTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THANH TOÁN");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setOpaque(false);

        lbMaXeTT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbMaXeTT.setText("Mã xe:");

        lbBienSoTT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbBienSoTT.setText("Biển số:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Thời gian vào: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Thời gian ra:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Tiền đã thu:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tổng cộng: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Tiền phải thu: ");

        txtMaXeTT.setEditable(false);
        txtMaXeTT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtBienSoTT.setEditable(false);
        txtBienSoTT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtThoiGianVaoTT.setEditable(false);
        txtThoiGianVaoTT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtThoiGianRaTT.setEditable(false);
        txtThoiGianRaTT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtSumTT.setEditable(false);
        txtSumTT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtTienDaThuTT.setEditable(false);
        txtTienDaThuTT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtTienPhaiThuTT.setEditable(false);
        txtTienPhaiThuTT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMaXeTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbBienSoTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTienDaThuTT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(txtThoiGianRaTT, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThoiGianVaoTT, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBienSoTT, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaXeTT, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSumTT)
                    .addComponent(txtTienPhaiThuTT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaXeTT)
                    .addComponent(txtMaXeTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBienSoTT)
                    .addComponent(txtBienSoTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtThoiGianVaoTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtThoiGianRaTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSumTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTienDaThuTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTienPhaiThuTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btexit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btexit.setText("X");
        btexit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btexitMouseExited(evt);
            }
        });
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmainLayout = new javax.swing.GroupLayout(panelmain);
        panelmain.setLayout(panelmainLayout);
        panelmainLayout.setHorizontalGroup(
            panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmainLayout.createSequentialGroup()
                .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelmainLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelmainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSubmitTT, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        panelmainLayout.setVerticalGroup(
            panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSubmitTT, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitTTActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "Xác nhận thanh toán ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION)
        {
            quanLyXe.updateXeDaRoi_Tien_Time(txtMaXeTT.getText(),Float.valueOf(txtSumTT.getText()));
        }
        this.dispose();
    }//GEN-LAST:event_btSubmitTTActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btexitActionPerformed

    private void btexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btexitMouseEntered
        // TODO add your handling code here:
        btexit.setBackground(Color.red);
        btexit.setForeground(Color.white);
    }//GEN-LAST:event_btexitMouseEntered

    private void btexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btexitMouseExited
        // TODO add your handling code here:
        btexit.setBackground(Color.WHITE);
        btexit.setForeground(Color.black);
    }//GEN-LAST:event_btexitMouseExited

    /**
     * @param args the command line arguments
     */
    
    public String stringToStringDate(String datetime){
        Date date=null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(datetime);
        } catch (ParseException ex) {
            System.out.println("Lõi chuyển ngày tháng");
        }
        
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm dd-MM-yyyy");
        String strDate = formatter.format(date);  
        return strDate;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSubmitTT;
    private javax.swing.JButton btexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbBienSoTT;
    private javax.swing.JLabel lbMaXeTT;
    private javax.swing.JPanel panelmain;
    private javax.swing.JTextField txtBienSoTT;
    private javax.swing.JTextField txtMaXeTT;
    private javax.swing.JTextField txtSumTT;
    private javax.swing.JTextField txtThoiGianRaTT;
    private javax.swing.JTextField txtThoiGianVaoTT;
    private javax.swing.JTextField txtTienDaThuTT;
    private javax.swing.JTextField txtTienPhaiThuTT;
    // End of variables declaration//GEN-END:variables
}
